name: cbir
channels:
- defaults
- conda-forge
dependencies:
- pylint=2.13.5
- flake8=4.0.1
- black=22.3.0
- conda-package-handling=1.8.1
- opencv=4.5.5
- jupyter=1.0.0
- pip=22.0.4
- matplotlib=3.5.1
- requests=2.27.1
- scikit-image=0.19.2
- ipympl=0.8.8
- pip:
  - ruamel-yaml==0.17.21

